services:
    App\Service\:
        resource: '../../src/Service'
        public: true
        autowire: true
    # Add Entity Repository as Service
    App\Repository\:
        resource: '../../src/Repository'
        tags:
            - 'doctrine.repository_service'
